_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 1

accelerator: cuda
devices: [0, 1, 2, 3]

# mixed precision for extra speed-up
# precision: 16

## perform a validation loop every N training epochs
#check_val_every_n_epoch: 0

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

strategy: ddp

log_every_n_steps: 10

num_sanity_val_steps: 5

val_check_interval: 1
